sonar.projectKey=employee-feedback
sonar.projectName=Employee Feedback
sonar.projectVersion=1.0

# Scan current project
sonar.sources=.

# Python version
sonar.python.version=3.12

# Encoding
sonar.sourceEncoding=UTF-8

# Ignore unnecessary files
sonar.exclusions=\
**/__pycache__/**,\
**/*.pyc,\
**/.git/**,\
**/mysql-init/**,\
**/nginx/**

# Ignore HTML coverage
sonar.coverage.exclusions=templates/**