sonar.projectKey=employee-feedback
sonar.projectName=Employee Feedback
sonar.projectVersion=1.0

# Analyze only app.py
sonar.sources=app.py

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
**/*.html,\
**/*.css,\
**/*.js,\
**/*.ts,\
**/*.sql,\
**/*.conf,\
**/__pycache__/**,\
**/*.pyc,\
**/.git/**,\
**/mysql-init/**,\
**/nginx/**